/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.smile {
    export class MyScrollItemUI extends View {
		public porkImage:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("smile/MyScrollItem");
        }
    }
    REG("ui.smile.MyScrollItemUI",MyScrollItemUI);
    export class MyScrollViewUI extends Scene {
		public container:Laya.Sprite;
		public leftBtn:Laya.Button;
		public rightBtn:Laya.Button;
		public nameText:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("smile/MyScrollView");
        }
    }
    REG("ui.smile.MyScrollViewUI",MyScrollViewUI);
}